---
title: "MSI figures"
author: "Harrison Anthony"
date: "4/29/2023"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message=FALSE,dev='png',dpi=300)
#knitr::opts_chunk$set(fig.path = 'C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/')

knitr::opts_knit$set(root.dir = 'C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/')
```

```{r libraries-and-functions}
#load libraries
library(tidyverse)
library(data.table)
library(UpSetR)
library(caret)
library(MLeval)
library(pROC)
library(gt)
library(tidyHeatmap)
library(ComplexHeatmap)
library(UpSetR)
library(rSRD)
library(ggpubr)
library(rstatix)
library(PreMSIm)
#create keys 

#create functions to read in the data for each msi tool
mantis <- function(prefix,tool,tcga,raw,fresh){
  file_list <- list.files(paste0(path='new_results/',prefix,'/',tool,'/'), full.names = TRUE,
                          recursive = FALSE)
  file_names <- list.files(paste0(path='new_results/',prefix,'/',tool,'/'), full.names = FALSE,
                           recursive = FALSE)
  
  if(tool=="msings"){
    file_names <- str_sub(file_names, end=-18)
  } else if (tool =="mantis"){
    file_names <- str_sub(file_names, end=-8)
    
  }
  
  
  results <- data.frame(samp_id=NA,score=NA,status=NA,
                        tot_sites=NA,binary=NA)
  for (i in 1:length(file_list)){
    temp <- fread(file_list[i])
    file_name <- file_names[i]
    
      if(tcga == TRUE){
      if(file_name %in% msih_wxs_key$filename | file_name %in% msih_wgs_key$filename){
        status="High"
        binary=1
      } else if( file_name %in% msil_wxs_key$filename | file_name %in% msil_wgs_key$filename){
        status="Stable"
        binary=0
      } else if (file_name %in% mss_wxs_key$filename | file_name %in% mss_wgs_key$filename){
        status="Stable"
        binary=0
      } else{status="ERROR"
      binary='ERROR'}
    } else if ( tcga == FALSE){
      
      
      temp20 <- filter(misc_key, samp_id == file_names[i]  )
      
      if(nrow(temp20)==0){
        next}
      else if(is.na(temp20$status)){
        status = NA
        binary = NA
      }else if(temp20$status == "MSIH"){
        status="High"
        binary= 1
      } else if (temp20$status =="MSS" | temp20$status == "MSIL"){
        status="Stable"
        binary=0
      } else { status="?"
      binary="?"}
      
    }
    
    temp2 <- data.frame(samp_id=file_name,
                        score=temp$Value[1],
                        status=status,
                        binary=binary,
                        tot_sites=NA)
    results <- rbind(results, temp2)
  }
  results <- results[-1,]
  if(raw==FALSE){
    temp21 <- filter(results, status != "NA") 
    temp21 <- filter(temp21, status != "?")
  }
  results <- temp21
  results$tool <- tool
  results$pseudonym <- paste0(prefix,'_',fresh)
  return(results)
}
sensor <- function(prefix,tool,tcga,raw,fresh){
  
  file_list <- list.files(paste0(path='new_results/',prefix,'/',tool,'/'), full.names = TRUE,
                          recursive = FALSE)
  file_names <- list.files(paste0(path='new_results/',prefix,'/',tool,'/'), full.names = FALSE,
                           recursive = FALSE)
  
  results <- data.frame(samp_id=NA,score=NA,status=NA,
                        tot_sites=NA,binary=NA)
  for (i in 1:length(file_list)){
    temp <- fread(file_list[i])
    file_name <- file_names[i]
    if(tcga == TRUE){
      if(file_name %in% msih_wxs_key$filename | file_name %in% msih_wgs_key$filename | file_name %in% msih_rna_key$`File Name`){
        status="High"
        binary=1
      } else if( file_name %in% msil_wxs_key$filename | file_name %in% msil_wgs_key$filename | file_name %in% msil_rna_key$`File Name`){
        status="Stable"
        binary=0
      } else if (file_name %in% mss_wxs_key$filename | file_name %in% mss_wgs_key$filename | file_name %in% mss_rna_key$`File Name`){
        status="Stable"
        binary=0
      } else{status="ERROR"
      binary='ERROR'}
    } else if ( tcga == FALSE){
      
      
      temp20 <- filter(misc_key, samp_id == file_names[i]  )
      if(nrow(temp20)==0){
        next}
      else if(is.na(temp20$status)){
        status = NA
        binary = NA
      }else if(temp20$status == "MSIH"){
        status="High"
        binary= 1
      } else if (temp20$status =="MSS" | temp20$status == "MSIL"){
        status="Stable"
        binary=0
      } else { status="?"
      binary="?"}
      
    }
    
    temp2 <- data.frame(samp_id=file_name,
                        score=temp$`%`,
                        status=status,
                        binary=binary,
                        tot_sites=temp$Total_Number_of_Sites)
    results <- rbind(results, temp2)
  }
  results <- results[-1,]
  if(raw==FALSE){
    temp21 <- filter(results, status != "NA") 
    temp21 <- filter(temp21, status != "?")
    temp21 <- filter(temp21, tot_sites > 0)
    
  }
  if(nrow(temp21) == 0){
    temp21 <- c("filtered out all data")
  }
  results <- temp21
  results$tool <- tool
  results$pseudonym <- paste0(prefix,'_',fresh)
  
  return(results)
}
msings <- function(prefix,tool,tcga,raw,fresh){
  
  
  file_list <- list.files(paste0(path='new_results/',prefix,'/',tool,'/'), full.names = TRUE,
                          recursive = FALSE)
  file_names <- list.files(paste0(path='new_results/',prefix,'/',tool,'/'), full.names = FALSE,
                           recursive = FALSE)
  
    file_names <- str_remove_all(file_names, ".MSI_analysis.txt")
    file_names <- str_remove_all(file_names, ".MSI_Analysis.txt")
    
results <- data.frame(samp_id=NA,score=NA,status=NA,
                        tot_sites=NA,binary=NA)
  for (i in 1:length(file_list)){
    temp <- fread(file_list[i])
    file_name <- file_names[i]
    if(tcga == TRUE){
      if(file_name %in% msih_wxs_key$filename | file_name %in% msih_wgs_key$filename | file_name %in% msih_rna_key$`File Name`){
        status="High"
        binary=1
      } else if( file_name %in% msil_wxs_key$filename | file_name %in% msil_wgs_key$filename | file_name %in% msil_rna_key$`File Name`) {
        status="Stable"
        binary=0
      } else if (file_name %in% mss_wxs_key$filename | file_name %in% mss_wgs_key$filename | file_name %in% mss_rna_key$`File Name`){
        status="Stable"
        binary=0
      } else{status="ERROR"
      binary='ERROR'}
    } else if ( tcga == FALSE){
      
      
      temp20 <- filter(misc_key, samp_id == file_names[i]  )
      if(nrow(temp20)==0){
        next}
      else if(is.na(temp20$status)){
        status = NA
        binary = NA
      }else if(temp20$status == "MSIH"){
        status="High"
        binary= 1
      } else if (temp20$status =="MSS" | temp20$status == "MSIL"){
        status="Stable"
        binary=0
      } else { status="?"
      binary="?"}
      
    }
    
    temp2 <- data.frame(samp_id=file_name,
                        score=as.numeric(temp[3,2]),
                        status=status,
                        binary=binary,
                        tot_sites=as.numeric(temp[1,2])+as.numeric(temp[2,2]))
    results <- rbind(results, temp2)
  }
  results <- results[-1,]
  
  if(raw==FALSE){
    temp21 <- filter(results, status != "NA") 
    temp21 <- filter(temp21, status != "?")
    temp21 <- filter(temp21, tot_sites > 0)
    
  }
  if(nrow(temp21) == 0){
    temp21 <- c("filtered out all data")
  }
  results <- temp21
  results$tool <- tool
  results$pseudonym <- paste0(prefix,'_',fresh)
  
  return(results)
}
msingb <- function(prefix,tool,tcga,raw,fresh){
  
    dir_list <- list.dirs(paste0(path='new_results/',prefix,'/',tool), full.names = TRUE,
                          recursive = FALSE)
  file_names <- list.files(paste0(path='new_results/',prefix,'/',tool,'/'), full.names = FALSE,
                           recursive = FALSE)
  
  results <- data.frame(samp_id=NA,score=NA,status=NA,
                        tot_sites=NA,binary=NA)
  
  for (i in 1:length(file_names)){
    temp <- fread(paste0(dir_list[i],'/preres.csv'))
    file_name <- file_names[i]
    if(tcga == TRUE){
      sample_sheet <- filter(all_rna_sample_sheet, `File Name` == file_name)
      case_id <- unlist(strsplit(sample_sheet$`Case ID`, ","))[1]
      if(case_id %in% msih_wxs_key$case_id | case_id%in% msih_wgs_key$case_id){
        status="High"
        binary=1
      } else if( case_id %in% msil_wxs_key$case_id | case_id %in% msil_wgs_key$case_id){
        status="Stable"
        binary=0
      } else if (case_id %in% mss_wxs_key$case_id | case_id %in% mss_wgs_key$case_id){
        status="Stable"
        binary=0
      } else{status="ERROR"
      binary='ERROR'}
    } else if ( tcga == FALSE){
      
      
      temp20 <- filter(misc_key, samp_id == file_names[i]  )
      if(nrow(temp20)==0){
        next}
      else if(is.na(temp20$status)){
        status = NA
        binary = NA
      }else if(temp20$status == "MSIH"){
        status="High"
        binary= 1
      } else if (temp20$status =="MSS" | temp20$status == "MSIL"){
        status="Stable"
        binary=0
      } else { status="?"
      binary="?"}
      
    }
    
    temp2 <- data.frame(samp_id=file_name,
                        score=temp$V2[2],
                        status=status,
                        binary=binary,
                        tot_sites=NA)
    results <- rbind(results, temp2)
  }
  results <- results[-1,]
  temp21 <- results
  if(raw==FALSE){
    temp21 <- filter(results, status != "NA") 
    temp21 <- filter(temp21, status != "?")
     }
  if(nrow(temp21) == 0){
    temp21 <- c("filtered out all data")
  }
  results <- temp21
  results$tool <- tool
  results$pseudonym <- paste0(prefix,'_',fresh)
  results$pcr_status <- results$status
  
  
  return(results)
}
premsim <- function(matrix,tool,tcga,raw,fresh){
  #set stage for premsim
path = system.file("extdata", "example.txt", package = "PreMSIm", mustWork = TRUE)
input_data = data_pre(path, type = "ID")

temp <- fread(matrix,header = TRUE)
temp2 <- temp
temp$gene_id <- NULL

temp3 <- t(as.matrix(temp,rownames.value=temp2$gene_id))

msi_results <- msi_pre(temp3[,c(colnames(input_data))])

msi_results$pcr_status <- NA
msi_results$binary <- NA

for(i in 1:nrow(msi_results)){
Sample <- msi_results$Sample[i]
if(tcga == TRUE){
      if(Sample %in% msih_rna_key$`File ID`){
        msi_results$pcr_status[i]="High"
        msi_results$binary[i]=1
      } else if( Sample %in% msil_rna_key$`File ID`){
        msi_results$pcr_status[i]="Stable"
        msi_results$binary[i]=0
      } else if (Sample %in% mss_rna_key$`File ID`){
        msi_results$pcr_status[i]="Stable"
        msi_results$binary[i]=0
      } else{msi_status$pcr_status[i]="ERROR"
      msi_results$binary[i]='ERROR'}
} else if (tcga == FALSE){
  temp20 <- filter(misc_key, samp_id == Sample)
      if(nrow(temp20)==0){
        next}
      else if(is.na(temp20$status)){
        status = NA
        binary = NA
      }else if(temp20$status == "MSIH"){
        status="High"
        binary= 1
      } else if (temp20$status =="MSS" | temp20$status == "MSIL"){
        status="Stable"
        binary=0
      } else { status="?"
      binary="?"}
  msi_results$pcr_status[i] <- status
msi_results$binary[i] <- binary
  
}


}
msi_results$score <- NA

for(i in 1:nrow(msi_results)){

if(msi_results$MSI_status[i] == 0){
  msi_results$score[i] <- 'MSS'
} else if (msi_results$MSI_status[i] == 1){
  msi_results$score[i] <- 'MSI-H'
} else {msi_results$score[i] <- 'ERROR'}
}
  if(raw==FALSE){
    temp21 <- filter(msi_results, pcr_status != "NA") 
    temp21 <- filter(temp21, pcr_status != "?")
     }
  if(nrow(temp21) == 0){
    temp21 <- c("filtered out all data")
  }
  msi_results <- temp21
return(msi_results)
  
  
}
sensor_rna <- function(matrix,tool,tcga,raw,fresh){
#read in matrix

  msi_results <- fread(matrix,header = TRUE)

msi_results$pcr_status <- NA
msi_results$binary <- NA

msi_results$Sample <- gsub(msi_results$sample_id,pattern='../',replacement='')
msi_results$score <- msi_results$msi_status
for(i in 1:nrow(msi_results)){
Sample <- msi_results$Sample[i]
if(tcga == TRUE){
      if(Sample %in% msih_rna_key$`File ID`){
        msi_results$pcr_status[i]="High"
        msi_results$binary[i]=1
      } else if( Sample %in% msil_rna_key$`File ID`){
        msi_results$pcr_status[i]="Stable"
        msi_results$binary[i]=0
      } else if (Sample %in% mss_rna_key$`File ID`){
        msi_results$pcr_status[i]="Stable"
        msi_results$binary[i]=0
      } else{msi_results$pcr_status[i]="ERROR"
      msi_results$binary[i]='ERROR'}
}
else if (tcga == FALSE){
  temp20 <- filter(misc_key, samp_id == Sample)
      if(nrow(temp20)==0){
        next} else if(is.na(temp20$status)){
        status = NA
        binary = NA
      }else if(temp20$status == "MSIH"){
        status="High"
        binary= 1
      } else if (temp20$status =="MSS" | temp20$status == "MSIL"){
        status="Stable"
        binary=0
      } else { status="?"
      binary="?"}
  msi_results$pcr_status[i] <- status
msi_results$binary[i] <- binary
  
}


}
  if(raw==FALSE){
    temp21 <- filter(msi_results, pcr_status != "NA") 
    temp21 <- filter(temp21, pcr_status != "?")
     }
  if(nrow(temp21) == 0){
    temp21 <- c("filtered out all data")
  }
  msi_results <- temp21

return(msi_results)
  
  
}



 #function to generate confusion matrix
confuse <- function(df, threshold,prefix,tool){
  if(tool == "MSINGB" | tool== "PreMSIm" | tool == "MSIsensor-RNA")
  {
       num_samps <- nrow(df)
  TP <- nrow(filter(df, score == 'MSI-H' & pcr_status == 'High'))
  FN <- nrow(filter(df, score == 'MSS' & pcr_status == 'High'))
  TN <- nrow(filter(df,score == 'MSS' & pcr_status == 'Stable'))
  FP <- nrow(filter(df, score == 'MSI-H' & pcr_status == 'Stable'))
  precision <- TP/(TP+FP)
  recall <- TP/(TP+FN)
  F1 <- (2*precision*recall)/(precision+recall)
  accuracy <- (TP+TN)/(TP+FN+TN+FP)
  specificity <- TN/(TN+FP)
                  data.frame(Dataset=prefix,
                             Tool=tool,
                             uniqueness=paste0(prefix,tool),
                             `Number of Samples`=num_samps,
                             TP = TP,
                             FP = FP,
                             TN = TN,
                             FN = FN,
                             "Precision"=precision,
                             "Recall"=recall,
                             "F1"=F1,
                             "Accuracy"=accuracy,
                             "Specificity"=specificity) %>% 
                    mutate(across(where(is.numeric), ~ round(., 3))) -> confusion_ha
     
     
    
    
  } else{
  
  
  num_samps <- nrow(df)
  TP <- nrow(filter(df, score >= threshold & status == 'High'))
  FN <- nrow(filter(df, score < threshold & status == 'High'))
  TN <- nrow(filter(df,score < threshold & status == 'Stable'))
  FP <- nrow(filter(df, score >= threshold & status == 'Stable'))
  precision <- TP/(TP+FP)
  recall <- TP/(TP+FN)
  F1 <- (2*precision*recall)/(precision+recall)
  accuracy <- (TP+TN)/(TP+FN+TN+FP)
  specificity <- TN/(TN+FP)
                  data.frame(Dataset=prefix,
                             Tool=tool,
                             uniqueness=paste0(prefix,tool),
                             `Number of Samples`=num_samps,
                             TP = TP,
                             FP = FP,
                             TN = TN,
                             FN = FN,
                             "Precision"=precision,
                             "Recall"=recall,
                             "F1"=F1,
                             "Accuracy"=accuracy,
                             "Specificity"=specificity) %>% 
                    mutate(across(where(is.numeric), ~ round(., 3))) -> confusion_ha
  }
  
  return(confusion_ha)}
#function to create upset plots
upsetter <- function(df){
  upset_df <- data.frame(samp_id=unique(df$samp_id))
upset_df$Pro <- NA
upset_df$Sensor <- NA
upset_df$Sensor2 <- NA
upset_df$MSIngs <- NA
upset_df$Mantis <- NA
upset_df$pseudnym <- NULL

for(i in 1:nrow(upset_df)){
 temp <-  filter(df, samp_id == upset_df$samp_id[i])
  if(nrow(temp) == 0){next}
 upset_df$pseudonym[i] <- temp$pseudonym[1]
 for(z in 1:nrow(temp)){
   if(temp$tool[z] == "pro" | temp$tool[z] =="sensor-pro"){
     if(temp$score[z] >=3.5 ){
       upset_df$Pro[i] <- 1
     }else if (temp$score[z] < 3.5){
       upset_df$Pro[i] <-0
     }else{upset_df$Pro[i]<-NA}
     
   } else if(temp$tool[z]=="msings"){
     if(temp$score[z] >= .2){
       upset_df$MSIngs[i] <- 1
     } else if(temp$score[z] < .2){
       upset_df$MSIngs[i] <- 0
     } else{ upset_df$MSIngs[i] <- NA}
       
   }  else if(temp$tool[z]=='sensor2'){
     if(temp$score[z] >=20 ){
       upset_df$Sensor2[i] <- 1
     } else if(temp$score[z] < 20 ){
       upset_df$Sensor2[i] <- 0
     } else {upset_df$Sensor2[i] <- NA}
     
   } else if (temp$tool[z]=='sensor'){
     if(temp$score[z] >= 3.5){
       upset_df$Sensor[i] <- 1
     } else if(temp$score[z]< 3.5){
       upset_df$Sensor[i] <- 0
     } else{upset_df$Sensor[i] <- NA}
   }
     
     else if (temp$tool[z]=='mantis'){
     if(temp$score[z] >= .4){
       upset_df$Mantis[i] <- 1
     } else if(temp$score[z]< .4){
       upset_df$Mantis[i] <- 0
     } else{upset_df$Mantis[i] <- NA}
     
   } else{}
 }
  
}
upset_df[is.na(upset_df)] = 0 
return(upset_df)
}





```

```{r get-keys}

#tcga keys
msih_wgs_key <- fread('master_keys/msih_wgs_master.manifest')
msil_wgs_key <- fread('master_keys/msil_wgs_master3.manifest')
mss_wgs_key <- fread('master_keys/mss_wgs_master2.manifest')
msih_wxs_key <- fread('master_keys/msih_wxs_master.manifest')
msil_wxs_key <- fread('master_keys/msil_wxs_master.manifest')
mss_wxs_key <- fread('master_keys/mss_wxs_master.manifest')
all_rna_sample_sheet <- fread('master_keys/all_rna_master_sample_sheet.tsv')
msih_rna_key <- fread('master_keys/rna_msih_manifest.tsv')
msil_rna_key <- fread('master_keys/rna_msil_manifest.tsv')
mss_rna_key <- fread ('master_keys/rna_mss_manifest.tsv')
#non-tcga keys
misc_key <- fread('misc_gt_updated2.tsv',header=T)
misc_key <- misc_key %>% mutate_all(na_if,"")



```

```{r tables}

non_tcga <- fread('C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/list_of_nontcga_datasets2.csv')
tcga <- fread('C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/list_of_datasets_for_pub2.csv')
tools <- fread('C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/list_of_tools.csv')
tcga |> gt() |> tab_header(title='Table 1',
                          subtitle = 'TCGA Datasets' )

non_tcga |> mutate(GT=NULL) |> gt() |> tab_header(title="Table 2",
                               subtitle="Non-TCGA Datasets")
tools |> gt() |> tab_header(title='table3',subtitle='Tool information')




```



```{r read-in-tcga-results}
wxs_pro <- sensor(prefix='A_wxs',tool='pro',tcga=TRUE,raw=FALSE,fresh='A_wxs')
wxs_sensor <- sensor(prefix='A_wxs',tool='sensor',tcga=TRUE,raw=FALSE,fresh='A_wxs')
wxs_sensor2 <- sensor(prefix='A_wxs',tool='sensor2',tcga=TRUE,raw=FALSE,fresh='A_wxs')
wxs_mantis <- mantis(prefix='A_wxs',tool='mantis',tcga=TRUE,raw=FALSE,fresh='A_wxs')
wxs_msings <- msings(prefix='A_wxs',tool='msings',tcga=TRUE,raw=FALSE,fresh='A_wxs')
wxs_msingb <- msingb(prefix='A_wxs',tool='msingb',tcga=TRUE,raw=FALSE,fresh='A_wxs')


wgs_pro <- sensor(prefix='A_wgs',tool='pro',tcga=TRUE,raw=FALSE,fresh='A_wgs')
wgs_sensor <- sensor(prefix='A_wgs',tool='sensor',tcga=TRUE,raw=FALSE,fresh='A_wgs')
wgs_sensor2 <- sensor(prefix='A_wgs',tool='sensor2',tcga=TRUE,raw=FALSE,fresh='A_wgs')
wgs_mantis <- mantis(prefix='A_wgs',tool='mantis',tcga=TRUE,raw=FALSE,fresh='A_wgs')
wgs_msings <- msings(prefix='A_wgs',tool='msings',tcga=TRUE,raw=FALSE,fresh='A_wgs')
wgs_msingb <- msingb(prefix='A_wgs',tool='msingb',tcga=TRUE,raw=FALSE,fresh='A_wgs')


rna_pro <- sensor(prefix="A_rna",tool="pro",tcga=TRUE,raw=FALSE,fresh="A_rna")
rna_sensor2 <- sensor(prefix='A_rna',tool='sensor2',tcga=TRUE,raw=FALSE,fresh='A_rna')
rna_msings <- msings(prefix='A_rna',tool='msings',tcga=TRUE,raw=FALSE,fresh='A_rna')
rna_premsim <- premsim('new_results/A_rna/premsim/A_rna.matrix',tcga=TRUE,raw=FALSE,fresh='A_rna',tool = 'premsim')
rna_sensor_rna <- sensor_rna('new_results/A_rna/sensor_rna/all_samples.txt',tcga=TRUE,tool = 'sensor_rna',raw = FALSE,fresh='A_rna')




```


```{r read-in-non-tcga-results}
genekor_pro <- sensor(prefix='genekor',tool = 'pro',tcga=FALSE,raw=FALSE,fresh="161panel")
genekor_msings <- msings(prefix='genekor',tool='msings',tcga=FALSE, raw=FALSE,fresh="161panel")
genekor_sensor2 <- sensor(prefix='genekor',tool='sensor2',tcga=FALSE, raw=FALSE,fresh="161panel")
genekor_msingb <- msingb(prefix = 'genekor',tool='msingb',tcga = FALSE,raw = FALSE,fresh = '161panel')


candiolo_pro <- sensor(prefix='candiolo',tool = 'pro',tcga=FALSE,raw=FALSE,fresh='to_wxs')
candiolo_msings <- msings(prefix='candiolo',tool='msings',tcga=FALSE, raw=FALSE,fresh='to_wxs')
candiolo_sensor2 <- sensor(prefix='candiolo',tool='sensor2',tcga=FALSE, raw=FALSE,fresh='to_wxs')
candiolo_msingb <- msingb(prefix='candiolo',tool='msingb',tcga=FALSE,raw=FALSE,fresh = 'to_wxs')


helicase_pro <- sensor(prefix='helicase',tool = 'pro',tcga=FALSE,raw=FALSE,fresh='endseq')
helicase_msings <- msings(prefix='helicase',tool='msings',tcga=FALSE, raw=FALSE,fresh='endseq')
helicase_sensor2 <- sensor(prefix='helicase',tool='sensor2',tcga=FALSE, raw=FALSE,fresh='endseq')
helicase_msingb <- msingb(prefix='helicase',tool = 'msingb',tcga=FALSE,raw=FALSE,fresh = 'endseq')

korea_pro <- sensor(prefix='korea',tool = 'pro',tcga=FALSE,raw=FALSE,fresh='wxs')
korea_msings <- msings(prefix='korea',tool='msings',tcga=FALSE, raw=FALSE,fresh='wxs')
korea_sensor2 <- sensor(prefix='korea',tool='sensor2',tcga=FALSE, raw=FALSE,fresh='wxs')
korea_mantis <- mantis(prefix='korea',tool='mantis',tcga=FALSE,raw=FALSE,fresh='wxs')
korea_sensor <- sensor(prefix='korea',tool='sensor',tcga=FALSE, raw=FALSE,fresh='wxs')
korea_msingb <- msingb(prefix='korea',tool='msingb',tcga=FALSE,raw=FALSE,fresh='wxs')


mgiseq_pro <- sensor(prefix='mgiseq',tool = 'pro',tcga=FALSE,raw=FALSE,fresh='6panel_marker')
mgiseq_msings <- msings(prefix='mgiseq',tool='msings',tcga=FALSE, raw=FALSE,fresh='6panel_marker')
mgiseq_sensor2 <- sensor(prefix='mgiseq',tool='sensor2',tcga=FALSE, raw=FALSE,fresh='6panel_marker')
mgiseq_mantis <- mantis(prefix='mgiseq',tool='mantis',tcga=FALSE, raw=FALSE,fresh='6panel_marker')
mgiseq_sensor<- sensor(prefix='mgiseq',tool='sensor',tcga=FALSE, raw=FALSE,fresh='6panel_marker')
mgiseq_msingb <- msingb(prefix='mgiseq',tool='msingb',tcga=FALSE,raw=FALSE,fresh='6panel_marker')

korea_rna_premsim <- premsim(matrix = 'C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/new_results/korea_rna/premsim/scaled_count_matrix.tsv',
                             tool='premsim',tcga=FALSE,raw=FALSE,fresh='korea_rna')
korea_rna_sensor_rna <- sensor_rna('C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/new_results/korea_rna/sensor_rna/all_samples.txt',
                             tool='sensor_rna',tcga = FALSE,raw=FALSE,fresh='korea_rna')
korea_rna_sensor2 <- sensor(prefix='korea_rna',tool='sensor2',tcga=FALSE, raw=FALSE,fresh='korea_rna')
korea_rna_msings <- msings(prefix='korea_rna',tool='msings',tcga=FALSE,raw=FALSE,fresh='korea_rna')
korea_rna_pro <- sensor(prefix='korea_rna',tool='pro',tcga=FALSE,raw=FALSE,fresh='korea_rna')




```
```{r tso500-results}

tso_results <- data.frame(samp_id=NA,score=NA,tot_sites=NA,status=NA,tool=NA)

rome_list <- c("58K","59K","60K","61K","63K","64K","65K","66K","67K","68K","69K","70K","71K","72K")
tso_sensor2_files <- list.files(path="C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/tso/tso/sensor2/", pattern="*", full.names=TRUE, recursive=FALSE)
tso_pro_files<- list.files(path="C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/tso/tso/pro/", pattern="*", full.names=TRUE, recursive=FALSE)
tso_msings_files <-list.files(path="C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/tso/tso/msings/", pattern="*", full.names=TRUE, recursive=FALSE)
#tso_msingb_files <- list.files(path='C:/Users/Harrison Anthony/Desktop/msi_benchmark_results/new_results/tso/)

for(i in tso_sensor2_files){
  temp <- fread(i)
  temp2 <- data.frame(samp_id=substr(i,74,nchar(i)),
                      score=temp$`%`,status="MSI-sensor2",
                      tot_sites=temp$Total_Number_of_Sites,
                      tool="sensor2")
  if(temp2$score > 20 ){
    temp2$status = "High"
  } else { temp2$status = "Stable"}
  
  
  
  tso_results <- rbind(tso_results,temp2)
}
for(i in tso_pro_files){
  temp <- fread(i)
  temp2 <- data.frame(samp_id=substr(i,70,nchar(i)),
                      score=temp$`%`,status="MSI-sensor pro",
                      tot_sites=temp$Total_Number_of_Sites,
                      tool="sensor-pro")
  if(temp2$score > 3.5 ){
    temp2$status = "High"
  } else { temp2$status = "Stable"}
  
  
  tso_results <- rbind(tso_results,temp2)
}

for(i in tso_msings_files){
  temp <- fread(i)
  temp2 <- data.frame(samp_id=substr(i,73,nchar(i)),
                      score= as.numeric(temp[3,2]),
                      tot_sites=as.numeric(temp[1,2])+
                        as.numeric(temp[1,2]),
                      tool="msings")
  if(nrow(temp)==3){
    temp2$status='NA'
  } else{
    if (temp[4,2] == "NEG"){
      temp2$status = "Stable"
    } else { temp2$status="High"}
    tso_results <- rbind(tso_results,temp2)
    
  }}


official_results <- fread(file = 'new_results/tso/official_tso_results.csv')

for(i in 1:nrow(official_results)){
  
  temp <- official_results[i,]
  
  temp2 <- data.frame(samp_id=temp$samp_id,
                      score= as.numeric(temp$msi_score),
                      tot_sites=as.numeric(temp$tot_sites),
                      tool="illumina")
  if(temp2$score >= 15){
    temp2$status <- "High"}
  else{
    temp2$status <- "Stable"
    
  }
  tso_results <- rbind(tso_results,temp2)
  
}


tso_results <- tso_results[-1,]

#tso_results$Status <- tso_results$status

tso <- tso_results
tso$pseudonym <- 'tso500'
tso$status <- 'Stable'
tso$status[c(1,8,18,19,39,52,58,68,69,89,102,106,116,117,137)] <- 'High'
tso_fin <- filter(tso, tool != 'illumina')
tso_fin %>%
  mutate(binary = if_else(status == 'Stable', 0,1)) -> tso_fin


tso_pro <- filter(tso_fin, tool=='sensor-pro')
tso_msings <- filter(tso_fin, tool=='msings')
tso_sensor2 <- filter(tso_fin, tool=='sensor2')
```
```{r create-confusion-matrices}


TCGA_all_confusion <- data.frame(rbind(
  confuse(df=wxs_pro,prefix = 'TCGA_WXS',threshold = 10,tool = 'MSIsensor-pro'),
  confuse(df=wxs_sensor,prefix = 'TCGA_WXS',threshold = 10,tool = 'MSIsensor'),
  confuse(df=wxs_sensor2,prefix = 'TCGA_WXS',threshold = 20,tool = 'MSIsensor2'),
  confuse(df=wxs_msings,prefix = 'TCGA_WXS',threshold = .2,tool = 'mSINGS'),
  confuse(df=wxs_mantis,prefix = 'TCGA_WXS',threshold = .4,tool = 'MANTIS'),
  confuse(df=wxs_msingb,prefix = 'TCGA_WXS',threshold = NA,tool = 'MSINGB'),

  confuse(df=wgs_pro,prefix = 'TCGA_WGS',threshold = 10,tool = 'MSIsensor-pro'),
  confuse(df=wgs_sensor,prefix = 'TCGA_WGS',threshold = 10,tool = 'MSIsensor'),
  confuse(df=wgs_sensor2,prefix = 'TCGA_WGS',threshold = 20,tool = 'MSIsensor2'),
  confuse(df=wgs_msings,prefix = 'TCGA_WGS',threshold = .2,tool = 'mSINGS'),
  confuse(df=wgs_mantis,prefix = 'TCGA_WGS',threshold = .4,tool = 'MANTIS'),
  confuse(df=wgs_msingb,prefix = 'TCGA_WGS',threshold = NA,tool = 'MSINGB'),

  confuse(df=rna_pro,prefix='TCGA_RNA',threshold=10,tool='MSIsensor-pro'),
  confuse(df=rna_sensor2,prefix='TCGA_RNA',threshold=20,tool='MSIsensor2'),
  confuse(df=rna_msings,prefix='TCGA_RNA',threshold=.2,tool='mSINGS'),
  confuse(df=rna_sensor_rna,prefix='TCGA_RNA',threshold=NA,tool = 'MSIsensor-RNA'),
  confuse(df=rna_premsim,prefix='TCGA_RNA',threshold=NA,tool = 'PreMSIm')))

  
  
 
 # TCGA_all_confusion$uniqueness
  
TCGA_all_confusion %>% rename("Number of samples"=Number.of.Samples) %>%
  mutate(uniqueness = NULL) %>%
  gt() |> tab_header(title="Table 3",subtitle="TCGA all samples confusion matrix")


panel_confusion <- data.frame(rbind(
 # confuse(df=tso_pro,prefix = 'TSO500',threshold = 10,tool = 'Pro'),
  #confuse(df=tso_sensor2,prefix = 'TSO500',threshold = 20,tool = 'Sensor2'),
  #confuse(df=tso_msings,prefix = 'TSO500',threshold = .2,tool = 'MSIngs'),
  
  #confuse(df=genekor_pro,prefix = '161 marker',threshold = 10,tool = 'Pro'),
  #confuse(df=genekor_sensor2,prefix = '161 marker',threshold = 20,tool = 'Sensor2'),
  #confuse(df=genekor_msings,prefix = '161 marker',threshold = .2,tool = 'MSIngs'),
  
  confuse(df=mgiseq_pro,prefix = '6 marker',threshold = 10,tool = 'MSIsensor-pro'),
  confuse(df=mgiseq_sensor,prefix = '6 marker',threshold = 10,tool = 'MSIsensor'),
  confuse(df=mgiseq_sensor2,prefix = '6 marker',threshold = 20,tool = 'MSIsensor2'),
  confuse(df=mgiseq_msings,prefix = '6 marker',threshold = .2,tool = 'mSINGS'),
  confuse(df=mgiseq_mantis,prefix = '6 marker',threshold = .4,tool = 'MANTIS')))


panel_confusion %>% rename("Number of samples"=Number.of.Samples) %>% 
  mutate(uniqueness= NULL) %>%
  gt() |> tab_header(title="Table 5",subtitle="All gene panel samples confusion matrix")

extra_confusion <- data.frame(rbind(
  confuse(df=candiolo_pro,prefix = 'T/O WXS',threshold = 10,tool = 'MSIsensor-pro'),
  confuse(df=candiolo_sensor2,prefix = 'T/O WXS',threshold = 20,tool = 'MSIsensor2'),
  confuse(df=candiolo_msings,prefix = 'T/O WXS',threshold = .2,tool = 'mSINGS'),
  confuse(df=candiolo_msingb,prefix='T/O WXS',threshold = NA,tool='MSINGB'),
  
  confuse(df=korea_pro,prefix = 'P/N WXS',threshold = 10,tool = 'MSIsensor-pro'),
  confuse(df=korea_sensor,prefix = 'P/N WXS',threshold = 10,tool = 'MSIsensor'),
  confuse(df=korea_sensor2,prefix = 'P/N WXS',threshold = 20,tool = 'MSIsensor2'),
  confuse(df=korea_msings,prefix = 'P/N WXS',threshold = .2,tool = 'mSINGS'),
  confuse(df=korea_mantis,prefix = 'P/N WXS',threshold = .4,tool = 'MANTIS'),
  confuse(df=korea_msingb,prefix='P/N WXS',threshold=NA,tool='MSINGB'),
  
  
  confuse(df=helicase_pro,prefix = 'End-seq',threshold = 10,tool = 'MSIsensor-pro'),
  confuse(df=helicase_sensor2,prefix = 'End-seq',threshold = 20,tool = 'MSIsensor2'),
  confuse(df=helicase_msings,prefix = 'End-seq',threshold = .2,tool = 'mSINGS'),
  confuse(df=helicase_msingb,prefix= 'End-seq',threshold = NA,tool='MSINGB'),
  
           
  confuse(df=mgiseq_pro,prefix = '6 marker',threshold = 10,tool = 'MSIsensor-pro'),
  confuse(df=mgiseq_sensor,prefix = '6 marker',threshold = 10,tool = 'MSIsensor'),
  confuse(df=mgiseq_sensor2,prefix = '6 marker',threshold = 20,tool = 'MSIsensor2'),
  confuse(df=mgiseq_msings,prefix = '6 marker',threshold = .2,tool = 'mSINGS'),
  confuse(df=mgiseq_mantis,prefix = '6 marker',threshold = .4,tool = 'MANTIS'),
  confuse(df=mgiseq_msingb,prefix='6 marker',threshold=NA,tool='MSINGB'),
  
  confuse(df=korea_rna_pro,prefix='RNA',threshold=10,tool='MSIsensor-pro'),
  confuse(df=korea_rna_sensor2,prefix='RNA',threshold = 20,tool='MSIsensor2'),
  confuse(df=korea_rna_msings,prefix='RNA',threshold=.2,tool='mSINGS'),
  confuse(df=korea_rna_premsim,prefix = 'RNA',threshold = NA,tool='PreMSIm'),
  confuse(df=korea_rna_sensor_rna,prefix='RNA',threshold=NA,tool='MSIsensor-RNA')))
  
  
 
extra_confusion %>% rename("Number of samples"=Number.of.Samples) %>% 
  mutate(uniqueness=NULL) %>%
  gt() |> tab_header(title="Table 4",subtitle="Additional datasets confusion matrix")



all_confusion <- rbind(confuse(df=rbind(wxs_pro,wgs_pro,rna_pro,mgiseq_pro,korea_pro,candiolo_pro,helicase_pro),prefix = 'All',threshold=10,tool='MSIsensor-pro'),
  confuse(df=rbind(wxs_sensor2,wgs_sensor2,rna_sensor2,mgiseq_sensor2,korea_sensor2,candiolo_sensor2,helicase_sensor2),prefix = 'All',threshold=20,tool='MSIsensor2'),
  confuse(df=rbind(wxs_msings,wgs_msings,rna_msings,mgiseq_msings,korea_msings,candiolo_msings,helicase_msings),prefix = 'All',threshold=.2,tool='mSINGS'),
  confuse(df=rbind(wxs_msingb,wgs_msingb,mgiseq_msingb,korea_msingb,candiolo_msingb,helicase_msingb),prefix = 'All',threshold=NA,tool='MSINGB'),
  confuse(df=rbind(wxs_sensor,wgs_sensor,mgiseq_sensor,korea_sensor),prefix = 'All',threshold=10,tool='MSIsensor'),
  confuse(df=rbind(wxs_mantis,wgs_mantis,mgiseq_mantis,korea_mantis),prefix = 'All',threshold=.4,tool='MANTIS'),
  confuse(df=rbind(rna_sensor_rna,korea_rna_sensor_rna),prefix = 'All',threshold=NA,tool='MSIsensor-RNA'),
    confuse(df=rbind(rna_premsim,korea_rna_premsim),prefix = 'All',threshold=NA,tool='PreMSIm'))

all_confusion %>% rename("Number of samples"=Number.of.Samples) %>% 
  mutate(uniqueness=NULL) %>%
  gt() |> tab_header(title="Table 4",subtitle="All data confusion matrix")






```
Figure 1 heatmap
```{r all-heatmap}


all_confuzed <- rbind(TCGA_all_confusion,
                      extra_confusion,
                      all_confusion)
#all_confuzed$Tool <- gsub(x = all_confuzed$Tool,pattern = 'Mantis',replacement = 'MANTIS',ignore.case = FALSE,fixed = TRUE)
##all_confuzed$Tool <- gsub(x = all_confuzed$Tool,pattern = 'Pro',replacement = 'MSIsensor-pro',ignore.case = FALSE,fixed = TRUE)
#all_confuzed$Tool <- gsub(x = all_confuzed$Tool,pattern = 'msings',replacement = 'mSINGS',ignore.case = FALSE,fixed = TRUE)
#all_confuzed$Tool <- gsub(x = all_confuzed$Tool,pattern = 'sensor2',replacement = 'MSIsensor2',ignore.case = FALSE,fixed = TRUE)
#all_confuzed$Tool <- gsub(x = all_confuzed$Tool,pattern = 'Sensor2',replacement = 'MSIsensor2',ignore.case = FALSE,fixed = TRUE)
##all_confuzed$Tool <- gsub(x = all_confuzed$Tool,pattern = 'Sensor',replacement = 'MSIsensor',ignore.case = FALSE,fixed = TRUE)
#all_confuzed$Tool <- gsub(x = all_confuzed$Tool,pattern = 'Sensor-RNA',replacement = 'MSIsensor-RNA',ignore.case = FALSE,fixed = TRUE)

all_confuzed %>% pivot_wider(id_cols = Dataset,names_from='Tool',values_from = (c('Precision','Recall','Specificity','Accuracy','F1'))) -> temp







trixy<- as.matrix(temp[,2:ncol(temp)])



        
        
Heatmap(t(trixy),na_col='darkkhaki',row_split = c(rep(unique(factor((all_confuzed$Tool))),5)),
        row_order=sort(rownames(trixy)),
        column_order = (sort(colnames(t(trixy)))),
        column_names_centered = TRUE,
        name="Value",
        column_split=c(temp$Dataset),
        cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.1f", t(trixy)[i, j]), x, y, gp = gpar(fontsize = 10))
})




```
```{r all-cv-roc}



set.seed(15827271)

 
      
#Leave out out crossvalidation settings
ctrl <- trainControl(method = "LOOCV",summaryFunction = prSummary,
                     classProbs = T,
                     savePredictions = T,
                     verboseIter = F)

#pro_idx <- createDataPartition(A_wxs_pro_results$status,p=.75,list=FALSE)
#pro_train <- A_wxs_pro_results[pro_idx,]
#pro_test <- A_wxs_pro_results[-pro_idx,]


fit_pro_wxs <- train(status ~ score, data = wxs_pro,
                     method='glm',trControl=ctrl, trace=FALSE,
                     family='binomial',metric='ROC')


fit_sensor_wxs <- train(status ~ score, data = wxs_sensor,
                        method='glm',trControl=ctrl, trace=FALSE,family='binomial',metric='ROC')
fit_sensor2_wxs <- train(status ~ score, data = wxs_sensor2,
                         method='glm',trControl=ctrl, trace=FALSE,family='binomial',metric='ROC')
fit_mantis_wxs <- train(status ~ score, data = wxs_mantis,
                        method='glm',trControl=ctrl, trace=FALSE,family='binomial',metric='ROC')
fit_msings_wxs <- train(status ~ score, data = wxs_msings,
                        method='glm',trControl=ctrl, trace=FALSE,family='binomial',metric='ROC')


fit_pro_rna <- train(status~score, data=rna_pro,
                     method='glm',trControl=ctrl,trace=FALSE,family='binomial',metric='ROC')
fit_sensor2_rna <- train(status~score, data=rna_sensor2,
                     method='glm',trControl=ctrl,trace=FALSE,family='binomial',metric='ROC')
fit_msings_rna <- train(status~score, data=rna_msings,
                     method='glm',trControl=ctrl,trace=FALSE,family='binomial',metric='ROC')



     
      
#ctrl <- trainControl(method="cv", number=10,
#                     summaryFunction = prSummary,
#                     classProbs = T,
#                     savePredictions = T,
#                     verboseIter = F)

fit_pro_wgs <- train(status ~ score, data = wgs_pro,
                     method='glm',
                     trControl=ctrl, trace=FALSE,family='binomial')

fit_sensor_wgs <- train(status ~ score, data = wgs_sensor,
                        method='glm',trControl=ctrl, trace=FALSE,family='binomial')
fit_sensor2_wgs <- train(status ~ score, data = wgs_sensor2,
                         method='glm',trControl=ctrl, trace=FALSE,family='binomial')
fit_mantis_wgs <- train(status ~ score, data = wgs_mantis,
                        method='glm', trControl=ctrl, trace=FALSE,family='binomial')
fit_msings_wgs <- train(status ~ score, data = wgs_msings,
                        method='glm', trControl=ctrl, trace=FALSE,family='binomial')

```

```{r WXS-roc-plots-cv}

models <- list("MSIsensor-pro" =fit_pro_wxs,"MSIsensor"=fit_sensor_wxs,"MSIsensor2"=fit_sensor2_wxs,"MANTIS"=fit_mantis_wxs,"mSINGS"=fit_msings_wxs)

models <- models[order(names(models))]

x <- evalm(models,
           positive='High',
                gnames=names(models))
                

##        #'Mantis','MSIngs')
```
```{r WGS-roc-plots-cv}
models <- list("MSIsensor-pro" =fit_pro_wgs,"MSIsensor"=fit_sensor_wgs,"MSIsensor2"=fit_sensor2_wgs,"MANTIS"=fit_mantis_wgs,"mSINGS"=fit_msings_wgs)

models <- models[order(names(models))]

x <- evalm(models,
           positive='High',
                gnames=names(models))

```
```{r RNA-roc-plots-cv}
models <- list("MSIsensor-pro" =fit_pro_rna,"MSIsensor2"=fit_sensor2_rna,
               "mSINGS"=fit_msings_rna)

models <- models[order(names(models))]

x <- evalm(models,
           positive='High',
                gnames=names(models))

```

```{r upset-plot,eval=FALSE}

all_df <- rbind(genekor_pro,genekor_msings,genekor_sensor2,candiolo_pro,candiolo_msings,candiolo_sensor2,helicase_pro,helicase_msings,helicase_sensor2,korea_sensor2,korea_pro,korea_msings,korea_sensor, korea_mantis,
                #miseq_pro,
                tso_fin,
                #miseq_msings,
                #miseq_sensor2,
                mgiseq_pro,mgiseq_mantis,mgiseq_msings,mgiseq_sensor,mgiseq_sensor2)


#remove msings string
all_df$samp_id <- str_remove_all  (all_df$samp_id, ".MSI_analysis.txt")
all_df$binary <- as.numeric(all_df$binary)

candiolo <- filter(all_df, pseudonym=='candiolo_to_wxs')

genekor <- filter(all_df, pseudonym=='genekor_161panel')

tso500 <- filter(all_df, pseudonym=='tso500')

endseq <- filter(all_df, pseudonym=='helicase_endseq')

korea <- filter(all_df, pseudonym=='korea_wxs')


mgii <- filter(all_df, pseudonym=='mgiseq_6panel_marker')

miseqq <- filter(all_df, pseudonym=='miseq_16markerpanel')

#candy <- upsetter(candiolo)
#gene <- upsetter(genekor)
##tso <- upsetter(tso500)
#end <- upsetter(endseq)
#kor <- upsetter(korea)
#mgi <- upsetter(mgii)
#miseq <- upsetter(miseqq)

all <- upsetter(all_df)
tso5002 <- upsetter(tso500)
tso5002$Mantis <- NULL
tso5002$Sensor <- NULL
tso5002$Illumina <- NA
for(i in 1:nrow(tso5002)){
  temp <- filter(tso_fin, samp_id == tso5002$samp_id[i])
  
  if(temp$status == 'Stable'){
    tso5002$Illumina[i] = 0 
    
  } else{tso5002$Illumina[i] = 1}
  
}
tso5002$pseudonym <- NULL

colnames(tso5002) <- c('samp_id','MSI-sensor pro','MSI-sensor 2','MSIngs','Illumina')




upset2 <- upset(tso5002,mainbar.y.label = "TSO500 Panel Intersctions", sets.x.label = "MSI-H cases per tool",text.scale =   c(3, 2, 1.8, 2, 2, 2.8))




genekor2 <- upsetter(genekor)
genekor2$Sensor <- NULL
genekor2$Mantis <- NULL
genekor$MSIcall <- NULL

for(i in 1:nrow(genekor2)){
  
  temp <- filter(misc_key, samp_id == genekor2$samp_id[i])
  if(temp$status == 'MSS'){
    genekor2$MSIcall[i]=0
  } else{ genekor2$MSIcall[i]=1}
  
  }
genekor2$pseudonym <- NULL

colnames(genekor2) <- c('samp_id','MSI-sensor pro','MSI-sensor 2', 'MSIngs','MSIcall')



upset1 <- upset(genekor2,mainbar.y.label = "161 Marker Panel Intersctions", sets.x.label = "MSI-H cases per tool",text.scale = c(3, 2, 1.8, 2, 2, 2.8))



```
```{r violin-plots,eval=FALSE}


filter(tso_results, tool != "illumina") %>% ggplot(aes(x=tool,y=score)) +
  geom_violin(draw_quantiles = c(0.5)) +
  #geom_boxplot(outlier.shape = NA) +
  theme_gray()+ labs(x="",y="MSI score")+facet_wrap(~tool,scales="free",
                    labeller=labeller(tool=c("sensor-pro" = "MSI-sensor Pro",
                                             "sensor2" = "MSI-sensor 2",
                                             "msings" = "MSIngs")),ncol=3)+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank() 
        ) +
  geom_jitter(aes(color=status), alpha = .5)
```


```{r rsd-wxs-compare-wgs,eval=FALSE}

###wxs

wxs_pro_scores <- data.frame(samp_id=wxs_pro$samp_id,wxs_pro$score)
wxs_sensor_scores <- data.frame(samp_id=wxs_sensor$samp_id,wxs_sensor$score)
wxs_sensor2_scores <- data.frame(samp_id=wxs_sensor2$samp_id,wxs_sensor2$score)
wxs_msings_scores <- data.frame(samp_id=wxs_msings$samp_id,wxs_msings$score)
wxs_mantis_scores <- data.frame(samp_id=wxs_mantis$samp_id,wxs_mantis$score)

temp1 <- merge(wxs_pro_scores,wxs_sensor_scores,by="samp_id")
temp2 <- merge(temp1,wxs_sensor2_scores,by="samp_id")
temp3 <- merge(temp2,wxs_msings_scores,by="samp_id")
temp4 <- merge(temp3,wxs_mantis_scores,by="samp_id")

temp4$case_id =NA

for(i in 1:nrow(temp4)){
  
 tryme <- filter(rbind(mss_wxs_key,msih_wxs_key,msil_wxs_key),filename == temp4$samp_id[i])
 temp4$case_id[i] <- tryme$case_id
  
}
wxs_presrd <- temp4

#filter down just to wgs samples

###wgs

  wgs_pro_scores <- data.frame(samp_id=wgs_pro$samp_id,wgs_pro$score)
  wgs_sensor_scores <- data.frame(samp_id=wgs_sensor$samp_id,wgs_sensor$score)
  wgs_sensor2_scores <- data.frame(samp_id=wgs_sensor2$samp_id,wgs_sensor2$score)
  wgs_msings_scores <- data.frame(samp_id=wgs_msings$samp_id,wgs_msings$score)
  wgs_mantis_scores <- data.frame(samp_id=wgs_mantis$samp_id,wgs_mantis$score)
  
  temp1 <- merge(wgs_pro_scores,wgs_sensor_scores,by="samp_id")
  temp2 <- merge(temp1,wgs_sensor2_scores,by="samp_id")
  temp3 <- merge(temp2,wgs_msings_scores,by="samp_id")
  temp4 <- merge(temp3,wgs_mantis_scores,by="samp_id")
  
temp4$case_id =NA

for(i in 1:nrow(temp4)){
  
 tryme <- filter(rbind(mss_wgs_key,msih_wgs_key,msil_wgs_key),filename == temp4$samp_id[i])
 temp4$case_id[i] <- tryme$case_id
  
}
wgs_presrd <- temp4

wxs_presrd <- filter(wxs_presrd, case_id %in% wgs_presrd$case_id)

#convert to ranks
#wxs_ranks <- utilsRankingMatrix(wxs_presrd[,2:6])
##colnames(wxs_ranks) <- c('Pro','Sensor','Sensor2','MSIngs','Mantis')
#utilsRankingMatrix(wxs_presrd[,2:6]) %>% rowMeans() -> wxs_presrd$rank_avg

#plotHeatmapSRD(wxs_ranks,output_to_file = FALSE)
#simulationData <- rSRD::calculateSRDDistribution(wxs_ranks)
#plotPermTest(wxs_ranks, simulationData)

#put wxs average rank to wgs
#wgs_presrd$wxs_avg_rank =-NA

#for(i in 1:nrow(wgs_presrd)){
#temp <- filter(wxs_presrd, case_id == wgs_presrd$case_id[i])
#if (nrow(temp) == 0 ){
#  wgs_presrd$wxs_avg_rank[i] <- NA
#  
#} else{
#wgs_presrd$wxs_avg_rank[i] <- temp$rank_avg
#}
  
  
#}

#wgs_presrd <- na.omit(wgs_presrd)
#wgs_ranks <- utilsRankingMatrix(wgs_presrd[,2:6])
#wgs_ranks$ref <- wgs_presrd$wxs_avg_rank
#colnames(wgs_ranks) <- c('Pro','Sensor','Sensor2','MSIngs','Mantis','ref')


#cv_results <- calculateCrossValidation(
#wgs_ranks,
#method = "Wilcoxon",
#number_of_folds = 10,
#output_to_file = FALSE
#)

#level_order <- c('Sensor2','Mantis','Pro','MSIngs','Sensor')
#cv_results$SRD_values_of_different_folds %>% 
#  pivot_longer(cols = colnames(cv_results$SRD_values_of_different_folds),
#               names_to = 'Tool',values_to = 'SRD') %>%
#  ggplot(aes(y=SRD,x=Tool))+
#  geom_boxplot(outlier.colour = 'red',outlier.shape=2,outlier.size=3)+
# stat_summary(fun.y=mean, geom="point", shape=1, size=3)+theme_classic()+
#  ggtitle('Figure 3',subtitle = 'TCGA WGS box plots of SRD values')+
#    theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))+
#    scale_x_discrete(limits = level_order) +ylab('SRD value')


```
```{r srd-and-boxplots,eval=FALSE}
wgs_presrd <- na.omit(wgs_presrd)
wgs_presrd <- filter(wgs_presrd, case_id %in% wxs_presrd$case_id)

wgs_presrd$ref_pro <- NA
wgs_presrd$ref_sensor <- NA
wgs_presrd$ref_sensor2 <- NA
wgs_presrd$ref_mantis <- NA
wgs_presrd$ref_msings <- NA

for(i in 1:nrow(wgs_presrd)){
  
  temp <- filter(wxs_presrd, case_id == wgs_presrd$case_id[i])
  wgs_presrd$ref_pro[i] <- temp$wxs_pro.score
  wgs_presrd$ref_sensor[i] <- temp$wxs_sensor.score
  wgs_presrd$ref_sensor2[i] <- temp$wxs_sensor2.score
  wgs_presrd$ref_msings[i] <- temp$wxs_msings.score
  wgs_presrd$ref_mantis[i] <- temp$wxs_mantis.score
  
  
}
#normalie msi score
#wgs_presrd$ref_mantis <- wgs_presrd$ref_mantis *100
#wgs_presrd$wgs_mantis.score <- wgs_presrd$wgs_mantis.score *100
#wgs_presrd$ref_msings <- wgs_presrd$ref_msings *100
#wgs_presrd$wgs_msings.score <- wgs_presrd$wgs_msings.score *100

  
wgs_presrd %>% rename("MSIsensor-pro" = wgs_pro.score,"MSIsensor"=wgs_sensor.score,
                     "MSIsensor2"=wgs_sensor2.score,
                     "mSINGS"=wgs_msings.score,
                     "MANTIS"=wgs_mantis.score,
                     "MSIsensor-pro ref" = ref_pro,"MSIsensor ref"=ref_sensor,
                    "MSIsensor2 ref"=ref_sensor2,
                     "mSINGS ref"=ref_msings,
                     "MANTIS ref"=ref_mantis ) %>%
  pivot_longer(cols=c("MSIsensor-pro","MSIsensor2", "mSINGS","MANTIS","MSIsensor","MSIsensor-pro ref", "MSIsensor2 ref","mSINGS ref","MANTIS ref","MSIsensor ref")
               ,names_to = 'Tool') -> wgs_presrd




wgs_presrd$seq <- NA

for(i in 1:nrow(wgs_presrd)){
temp <- wgs_presrd[i,]
if(temp$Tool == "MSI-sensor pro" |
   temp$Tool == "MSI-sensor" | 
   temp$Tool == "MSIngs" |
   temp$Tool == "MANTIS" | 
   temp$Tool == "MSI-sensor 2"){
  wgs_presrd$seq[i] <- "WGS"
   } else { wgs_presrd$seq[i] <- "WXS"}
  
  
  
}
wgs_presrd$Tool <- gsub(wgs_presrd$Tool,pattern = ' ref',replacement =  '')



 # ggplot(data = wgs_presrd,aes(y=value,x=Tool,fill=seq))+
#  geom_boxplot(outlier.colour = 'red',outlier.shape=2,outlier.size=3)+
#    stat_pvalue_manual(wgs_presrd %>% 
#                       pairwise_wilcox_test(value ~ Tool) %>% 
#                       add_xy_position())
#  +stat_summary(fun.y=mean, geom="point", shape=1, size=3)+theme_classic()+
 # ggtitle('Figure 3',subtitle = 'TCGA WGS box plots of SRD values')+
  #  theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))+
  #  scale_x_discrete(limits = level_order) +ylab('SRD value')
  # Decide the order of groups in the argument levels
wgs_presrd$seq <- factor(wgs_presrd$seq,levels=c('WXS','WGS'))
 wgs_presrd %>%
      ggpaired(x='seq',y='value', id = "case_id",
         color = "seq", line.color = "gray90", line.size = .01,
         palette = "jco")+
  stat_compare_means(paired = TRUE,vjust=-1)+  facet_wrap(~Tool,scales="free_y",nrow=1)+theme_classic()+
 ggtitle('Figure 3',subtitle = 'TCGA Boxplots of MSI Scores')+ ylab('MSI-score')+xlab('Sequencing type')+
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))+ theme(legend.position = "none")

 
 
  wgs_presrd %>%
      ggpaired(x='seq',y='value', id = "case_id",
         color = "seq", line.color = "gray90", line.size = .01,
         palette = "jco")+
  stat_compare_means(paired = TRUE,vjust=-1)+  facet_wrap(~Tool,scales="free_y",nrow=1)+theme_classic()+
  ylab('MSI-score')+xlab('Sequencing type')+ theme(legend.position = "none")+
    theme(strip.text.x = element_text(size = 12)) 


```




```{r pairwise-srd,eval=FALSE}

###wxs

wxs_pro_scores <- data.frame(samp_id=wxs_pro$samp_id,wxs_pro$score)
wxs_sensor_scores <- data.frame(samp_id=wxs_sensor$samp_id,wxs_sensor$score)
wxs_sensor2_scores <- data.frame(samp_id=wxs_sensor2$samp_id,wxs_sensor2$score)
wxs_msings_scores <- data.frame(samp_id=wxs_msings$samp_id,wxs_msings$score)
wxs_mantis_scores <- data.frame(samp_id=wxs_mantis$samp_id,wxs_mantis$score)

temp1 <- merge(wxs_pro_scores,wxs_sensor_scores,by="samp_id")
temp2 <- merge(temp1,wxs_sensor2_scores,by="samp_id")
temp3 <- merge(temp2,wxs_msings_scores,by="samp_id")
temp4 <- merge(temp3,wxs_mantis_scores,by="samp_id")

temp4$case_id =NA

for(i in 1:nrow(temp4)){
  
 tryme <- filter(rbind(mss_wxs_key,msih_wxs_key,msil_wxs_key),filename == temp4$samp_id[i])
 temp4$case_id[i] <- tryme$case_id
  
}
wxs_presrd <- temp4

#filter down just to wgs samples

###wgs

  wgs_pro_scores <- data.frame(samp_id=wgs_pro$samp_id,wgs_pro$score)
  wgs_sensor_scores <- data.frame(samp_id=wgs_sensor$samp_id,wgs_sensor$score)
  wgs_sensor2_scores <- data.frame(samp_id=wgs_sensor2$samp_id,wgs_sensor2$score)
  wgs_msings_scores <- data.frame(samp_id=wgs_msings$samp_id,wgs_msings$score)
  wgs_mantis_scores <- data.frame(samp_id=wgs_mantis$samp_id,wgs_mantis$score)
  
  temp1 <- merge(wgs_pro_scores,wgs_sensor_scores,by="samp_id")
  temp2 <- merge(temp1,wgs_sensor2_scores,by="samp_id")
  temp3 <- merge(temp2,wgs_msings_scores,by="samp_id")
  temp4 <- merge(temp3,wgs_mantis_scores,by="samp_id")
  
temp4$case_id =NA

for(i in 1:nrow(temp4)){
  
 tryme <- filter(rbind(mss_wgs_key,msih_wgs_key,msil_wgs_key),filename == temp4$samp_id[i])
 temp4$case_id[i] <- tryme$case_id
  
}
wgs_presrd <- temp4

#convert to ranks
wxs_ranks <- utilsRankingMatrix(wxs_presrd[,2:6])
colnames(wxs_ranks) <- c('MSI-sensor pro','MSI-sensor','MSI-sensor2','MSIngs','MANTIS')
#plotHeatmapSRD(wxs_ranks,output_to_file = TRUE)



wgs_ranks <- utilsRankingMatrix(wgs_presrd[,2:6])
colnames(wgs_ranks) <- c('MSI-sensor pro','MSI-sensor','MSI-sensor2','MSIngs','MANTIS')
#plotHeatmapSRD(wgs_ranks,output_to_file = TRUE)

wxs_dist_matrix <- as.matrix(fread('C:/Users/Harrison Anthony/Downloads/SRDdistanceMatrix_wxs.csv'),rownames=1)
wgs_dist_matrix <- as.matrix(fread('C:/Users/Harrison Anthony/Downloads/SRDdistanceMatrix_wgs.csv'),rownames=1)

Heatmap(wgs_dist_matrix,cluster_columns=FALSE,
        cluster_rows=FALSE,column_names_centered = TRUE,
        name="Manhattan distance",cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.1f", wgs_dist_matrix[i, j]), x, y, gp = gpar(fontsize = 10))
})
Heatmap(wxs_dist_matrix,cluster_columns=FALSE,column_names_centered = TRUE,
        name="Manhattan distance",
        cluster_rows=FALSE,cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.1f", wxs_dist_matrix[i, j]), x, y, gp = gpar(fontsize = 10))
})









```


```{r precision-thresh-tradeoff,eval=FALSE}




mantis_thres <- seq(0,1, by=.01)
sensor_thresh <-seq(0,100,by=1)
sensor2_thresh <-seq(0,100,by=1)
pro_thresh <-seq(0,100,by=1)
msings_thresh <- seq(0,1,by=.01)

final_df <- confuse(df=korea_mantis,prefix='P/N_WXS',threshold=mantis_thres[i],tool='Mantis')
final_df$threshold <- NA




for(i in 1:length(mantis_thres)){
  temp <- confuse(df=korea_mantis,prefix='P/N_WXS',threshold=mantis_thres[i],tool='Mantis')
  temp$threshold <- mantis_thres[i]
  final_df <- rbind(final_df,temp)
  temp <- confuse(df=mgiseq_mantis,prefix='6 panel',threshold=mantis_thres[i],tool='Mantis')
    temp$threshold <- mantis_thres[i]
  final_df <- rbind(final_df,temp)
}

for(i in 1:length(sensor_thresh)){
  temp <- confuse(df=korea_sensor,prefix='P/N_WXS',threshold=sensor_thresh[i],tool='Sensor')
  temp$threshold <- sensor_thresh[i]/100
  final_df <- rbind(final_df,temp)
  temp <- confuse(df=mgiseq_sensor,prefix='6 panel',threshold=sensor_thresh[i],tool='Sensor')
    temp$threshold <- sensor_thresh[i]/100
  final_df <- rbind(final_df,temp)
}


for(i in 1:length(sensor2_thresh)){
  temp <- confuse(df=korea_sensor2,prefix='P/N_WXS',threshold=sensor2_thresh[i],tool='sensor2')
  temp$threshold <- sensor2_thresh[i]/100
  final_df <- rbind(final_df,temp)
  temp <- confuse(df=mgiseq_sensor2,prefix='6 panel',threshold=sensor2_thresh[i],tool='sensor2')
    temp$threshold <- sensor2_thresh[i]/100
  final_df <- rbind(final_df,temp)
  
  temp <- confuse(df=candiolo_sensor2,prefix='T/O_WXS',threshold=sensor2_thresh[i],tool='Sensor2')
  temp$threshold <- sensor2_thresh[i]/100
  final_df <- rbind(final_df, temp)
  
  temp <- confuse(df=helicase_sensor2,prefix='End-seq',threshold=sensor2_thresh[i],tool='Sensor2')
  temp$threshold <- sensor2_thresh[i]/100
  final_df <- rbind(final_df,temp)
}

for(i in 1:length(pro_thresh)){
  temp <- confuse(df=korea_pro,prefix='P/N_WXS',threshold=pro_thresh[i],tool='pro')
  temp$threshold <- pro_thresh[i]/100
  final_df <- rbind(final_df,temp)
  temp <- confuse(df=mgiseq_pro,prefix='6 panel',threshold=pro_thresh[i],tool='pro')
    temp$threshold <- pro_thresh[i]/100
  final_df <- rbind(final_df,temp)
  
  temp <- confuse(df=candiolo_pro,prefix='T/O_WXS',threshold=pro_thresh[i],tool='pro')
  temp$threshold <- pro_thresh[i]/100
  final_df <- rbind(final_df, temp)
  
  temp <- confuse(df=helicase_pro,prefix='End-seq',threshold=pro_thresh[i],tool='pro')
  temp$threshold <- pro_thresh[i]/100
  final_df <- rbind(final_df,temp)
}
for(i in 1:length(msings_thresh)){
  temp <- confuse(df=korea_msings,prefix='P/N_WXS',threshold=msings_thresh[i],tool='msings')
  temp$threshold <- msings_thresh[i]
  final_df <- rbind(final_df,temp)
  temp <- confuse(df=mgiseq_msings,prefix='6 panel',threshold=msings_thresh[i],tool='msings')
    temp$threshold <- msings_thresh[i]
  final_df <- rbind(final_df,temp)
  
  temp <- confuse(df=candiolo_msings,prefix='T/O_WXS',threshold=msings_thresh[i],tool='msings')
  temp$threshold <- msings_thresh[i]
  final_df <- rbind(final_df, temp)
  
  temp <- confuse(df=helicase_msings,prefix='End-seq',threshold=msings_thresh[i],tool='msings')
  temp$threshold <- msings_thresh[i]
  final_df <- rbind(final_df,temp)
}

final_df <- final_df[-1,]

final_df[is.na(final_df)] <- 0

final_df$Tool <- gsub(x = final_df$Tool,pattern = 'Mantis',replacement = 'MANTIS',ignore.case = FALSE,fixed = TRUE)
final_df$Tool <- gsub(x = final_df$Tool,pattern = 'pro',replacement = 'MSIsensor-pro',ignore.case = FALSE,fixed = TRUE)
final_df$Tool <- gsub(x = final_df$Tool,pattern = 'msings',replacement = 'mSINGS',ignore.case = FALSE,fixed = TRUE)
final_df$Tool <- gsub(x = final_df$Tool,pattern = 'sensor2',replacement = 'MSIsensor2',ignore.case = FALSE,fixed = TRUE)
final_df$Tool <- gsub(x = final_df$Tool,pattern = 'Sensor2',replacement = 'MSIsensor2',ignore.case = FALSE,fixed = TRUE)
final_df$Tool <- gsub(x = final_df$Tool,pattern = 'Sensor',replacement = 'MSIsensor',ignore.case = FALSE,fixed = TRUE)

final_df$Dataset <- gsub(x=final_df$Dataset,pattern="P/N_WXS",replacement="P/N WXS")
final_df$Dataset <- gsub(x=final_df$Dataset,pattern="T/O_WXS",replacement="T/O WXS")

ggplot(final_df,aes(x=threshold,y=F1,color=Tool))+
  geom_line()+facet_wrap(~Dataset
                         )+theme_pubr()+
 #('Figure 5',subtitle = 'Performance on additional datasets by threhsold')+
  xlab('Threshold')+
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))



ggplot(final_df,aes(x=threshold,y=Precision,color=Tool))+
  geom_line()+facet_wrap(~Dataset
                         )+theme_pubr()+
 #('Figure 5',subtitle = 'Performance on additional datasets by threhsold')+
  xlab('Threshold')+
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))


ggplot(final_df,aes(x=threshold,y=Specificity,color=Tool))+
  geom_line()+facet_wrap(~Dataset
                         )+theme_pubr()+
 #('Figure 5',subtitle = 'Performance on additional datasets by threhsold')+
  xlab('Threshold')+
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))


ggplot(final_df,aes(x=threshold,y=Accuracy,color=Tool))+
  geom_line()+facet_wrap(~Dataset
                         )+theme_pubr()+
 #('Figure 5',subtitle = 'Performance on additional datasets by threhsold')+
  xlab('Threshold')+
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))


ggplot(final_df,aes(x=threshold,y=Recall,color=Tool))+
  geom_line()+facet_wrap(~Dataset
                         )+theme_pubr()+
 #('Figure 5',subtitle = 'Performance on additional datasets by threhsold')+
  xlab('Threshold')+
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust=.5))





```

